# Generated by Django 4.0.4 on 2022-05-28 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
        ('profiles', '0001_initial'),
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('requested_delivery_date', models.DateTimeField(default=None)),
                ('weight', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('not shipped', 'не доставлено'), ('shipped', 'доставлено')], default='не доставлено', max_length=255)),
                ('courier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courier_orders', to='couriers.courier')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='profiles.customer')),
                ('order_item', models.ManyToManyField(default=None, to='mystore.product')),
            ],
        ),
    ]
