# Generated by Django 4.0.4 on 2022-05-28 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(db_index=True, max_length=255)),
                ('destination', models.CharField(db_index=True, max_length=255)),
                ('weight', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('not shipped', 'не доставлено'), ('shipped', 'доставлено')], default='не доставлено', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
