# Generated by Django 4.0.4 on 2022-05-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(to='mystore.product'),
        ),
    ]
