# Generated by Django 4.0.4 on 2022-05-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='requested_delivery_date',
        ),
    ]
