# Generated by Django 4.0.4 on 2022-05-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_remove_order_requested_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
