# Generated by Django 4.0.4 on 2022-05-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
        ('profiles', '0001_initial'),
        ('mystore', '0005_remove_order_courier_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='courier_orders', to='couriers.courier'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='profiles.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(blank=True, default='1', to='mystore.product'),
        ),
    ]
