# Generated by Django 4.0.4 on 2022-05-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0006_order_courier_order_customer_order_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_item',
        ),
    ]
